# Generated by Django 2.2.6 on 2019-11-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow')], max_length=50, null=True)),
                ('posicion', models.CharField(blank=True, choices=[('DelSuperiorD', 'DelSuperiorD'), ('DelSuperiorI', 'DelSuperiorI'), ('DelInferiorD', 'DelInferiorD'), ('DelInferiorI', 'DelInferiorI'), ('TrasSuperiorD', 'TrasSuperiorD'), ('TrasSuperiorI', 'TrasSuperiorI'), ('TrasInferiorD', 'TrasInferiorD'), ('TrasInferiorI', 'TrasInferiorI')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='opciones')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamano', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], max_length=50)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow')], max_length=50)),
                ('diseno', models.ManyToManyField(through='ropa.Asignacion', to='ropa.Diseno')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ropa.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='diseno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ropa.Diseno'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ropa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ropa.Ropa'),
        ),
    ]
