# Generated by Django 2.2.6 on 2019-11-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('ropa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('re', 'recibido'), ('pa', 'pagado'), ('en', 'entregado')], default='re', max_length=4)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.Orden')),
                ('ropa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ropa.Ropa')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='ropa',
            field=models.ManyToManyField(through='factura.OrdenDetail', to='ropa.Ropa'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pago', models.CharField(choices=[('cs', 'cash'), ('ca', 'card'), ('cu', 'cupon')], max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factura.Orden')),
            ],
        ),
    ]
